# Generated by Django 2.0.6 on 2019-09-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_con', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'カテゴリ', 'verbose_name_plural': 'カテゴリ'},
        ),
        migrations.AlterModelOptions(
            name='remote_con',
            options={'verbose_name': 'コントローラー', 'verbose_name_plural': 'コントローラー'},
        ),
        migrations.AlterField(
            model_name='remote_con',
            name='category',
            field=models.IntegerField(verbose_name='縦の角度'),
        ),
        migrations.AlterField(
            model_name='remote_con',
            name='memo',
            field=models.BinaryField(verbose_name='赤外線の値'),
        ),
        migrations.AlterField(
            model_name='remote_con',
            name='money',
            field=models.IntegerField(verbose_name='横の角度'),
        ),
    ]
