# Generated by Django 2.0.6 on 2019-09-09 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remote_con', '0002_auto_20190909_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remote_con',
            old_name='money',
            new_name='horizontal_angle',
        ),
        migrations.RenameField(
            model_name='remote_con',
            old_name='memo',
            new_name='infrared',
        ),
        migrations.RenameField(
            model_name='remote_con',
            old_name='date',
            new_name='machine_name',
        ),
        migrations.RenameField(
            model_name='remote_con',
            old_name='category',
            new_name='vertical_angle',
        ),
    ]
