# Generated by Django 2.0.6 on 2019-09-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remote_con', '0003_auto_20190909_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remote_con',
            options={'verbose_name': 'リモコン', 'verbose_name_plural': 'リモコン'},
        ),
        migrations.AlterModelTable(
            name='remote_con',
            table='remote_con',
        ),
    ]
