# Generated by Django 2.0.6 on 2019-09-09 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Remote_con',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=500, verbose_name='機器の名前')),
                ('money', models.IntegerField(verbose_name='角度')),
                ('memo', models.IntegerField(max_length=500, verbose_name='赤外線の値')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='remote_con.Category', verbose_name='カテゴリ')),
            ],
            options={
                'db_table': 'controller',
            },
        ),
    ]
